// LAYOUT
export const LAYOUT_SET_MENUKEYS = 'LAYOUT_SET_MENUKEYS';
export const LAYOUT_SHOW_SIDEMENU = 'LAYOUT_SHOW_SIDEMENU';
export const LAYOUT_HIDE_SIDEMENU = 'LAYOUT_HIDE_SIDEMENU';
export const LAYOUT_SHOW_MOBILEMENU = 'LAYOUT_SHOW_MOBILEMENU';
export const LAYOUT_HIDE_MOBILEMENU = 'LAYOUT_HIDE_MOBILEMENU';
